# Generated by Django 4.2.7 on 2025-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_ressource_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressource',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
