# Generated by Django 4.2.7 on 2025-08-28 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_ressource_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_email', models.EmailField(max_length=254)),
                ('reason', models.TextField(blank=True, help_text='Raison de la demande de réinitialisation')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSED', 'Traitée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Notes de l'administrateur")),
                ('new_password_sent', models.BooleanField(default=False)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_password_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de réinitialisation de mot de passe',
                'verbose_name_plural': 'Demandes de réinitialisation de mot de passe',
                'ordering': ['-created_at'],
            },
        ),
    ]
