# Generated by Django 5.2.5 on 2025-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute'), ('Critique', 'Critique')], max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('À initier', 'À initier'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Suspendu', 'Suspendu'), ('Annulé', 'Annulé')], max_length=20, verbose_name='Statut'),
        ),
    ]
