# Generated by Django 4.2.7 on 2025-09-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('À initier', 'À initier'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Suspendu', 'Suspendu'), ('Annulé', 'Annulé')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Status Log',
                'verbose_name_plural': 'Project Status Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
