# Generated by Django 4.2.7 on 2025-08-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_done',
            field=models.BooleanField(default=False, help_text='True if activity is completed, False if pending'),
        ),
    ]
