# Generated by Django 4.2.10 on 2025-08-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_done',
        ),
    ]
