# Generated by Django 4.2.7 on 2025-08-26 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0003_remove_activity_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('log_type', models.CharField(choices=[('SCHEDULED', 'Scheduled Activity'), ('COMPLETED', 'Completed Activity'), ('CANCELLED', 'Cancelled Activity')], max_length=10)),
                ('allocation_status', models.CharField(choices=[('ALLOCATED', 'Allocated Time'), ('AVAILABLE', 'Available Time')], max_length=10)),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('activity_title', models.CharField(blank=True, max_length=200)),
                ('planned_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('efficiency_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='activities.activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_hour'],
                'indexes': [models.Index(fields=['employee', 'date'], name='activities__employe_1be0fd_idx'), models.Index(fields=['date', 'allocation_status'], name='activities__date_b2adf5_idx'), models.Index(fields=['employee', 'log_type'], name='activities__employe_e0030c_idx')],
            },
        ),
    ]
