# Generated by Django 4.2.7 on 2025-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(verbose_name='Description détailée')),
                ('type', models.CharField(choices=[('BUILD', 'Projet (BUILD)'), ('RUN', 'RUN')], max_length=20, verbose_name='Type de projet')),
                ('status', models.CharField(choices=[('À initier', 'To init'), ('En cours', 'In progress'), ('Terminé', 'Finished'), ('Suspendu', 'Suspended'), ('Annulé', 'Cancelled')], max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('Basse', 'Low'), ('Moyenne', 'Medium'), ('Haute', 'High'), ('Critique', 'Critical')], max_length=20, verbose_name='Priorité')),
                ('expected_start_date', models.DateField(verbose_name='Date de début prévue')),
                ('expected_end_date', models.DateField(verbose_name='Date de fin prévue')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début réelle')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('estimated_charges', models.IntegerField(verbose_name='Charges estimées (en jours ou heures)')),
                ('progress', models.IntegerField(verbose_name='Avancement (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
