# Generated by Django 5.2.5 on 2025-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_created_by_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin réelle'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début réelle'),
        ),
    ]
