# Generated by Django 4.2.7 on 2025-09-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_ticket_end_date_ticket_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('Résolu', 'Résolu'), ('Fermé', 'Fermé')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Status Log',
                'verbose_name_plural': 'Ticket Status Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
